### PR TITLE
XSS Automation

### PR DESCRIPTION
**Pull request by fanimalikhack**

### CODE REVIEW

**Comment by fanimalikhack** [comment]
XSS Automation

**Comment by grampae** [comment]
This looks pretty cool, however when I try to use this gf does not have a native pattern file called xss and fails.
Do you have a custom pattern that you are using and if so would you mind sharing?

**Comment by fanimalikhack** [comment]
here is all Gf Patterns https://github.com/1ndianl33t/Gf-Patterns

if you already have urls.txt  this will append new urls in the last of  urls.txt ```target.com >> tee urls.txt``` . 
but this will create a new urls.txt  ```waybackurls target.com | tee urls.txt```

**Comment by grampae** [comment]
> here is all Gf Patterns https://github.com/1ndianl33t/Gf-Patterns
> 
> if you already have urls.txt this will append new urls in the last of urls.txt `target.com >> tee urls.txt` .
> but this will create a new urls.txt `waybackurls target.com | tee urls.txt`

Awesome thank you!!

**Comment by bugpie54** [comment]
# -a flag can be used to append urls to urls.txt file
waybackurls target.com | tee -a urls.txt
This is a Gf-pattern that has xss.json & sqli.json updated recently: https://github.com/six2dez/Gf-Patterns

**Comment by bugpie54** [comment]
-a flag can be used to append urls to urls.txt file
waybackurls target.com | tee -a urls.txt

**Comment by bugpie54** [comment]
-a flag can be used to append urls to urls.txt file
```waybackurls target.com | tee -a urls.txt```
OR
```waybackurls target.com >> urls.txt```

**Pull request closed without merging**
