### PR TITLE
Merge AWSome Pentesting into Cloud - AWS Pentest

### PR DESCRIPTION
**Pull request by pop3ret**
Merge the notes with the existing one

### CODE REVIEW

**Review by pop3ret — COMMENTED** [review]
Everything ok!

**Comment by pop3ret** [comment]
Hey, do you need something else in my side to be done? Just wanting to help

**Comment by swisskyrepo** [comment]
I think we need to update the Summary and to move the current content into their corresponding chapters before merging 🤗

**Comment by pop3ret** [comment]
Sure!! Let me do it, I will send a pull request with the changes, Thank you!

**Comment by pop3ret** [comment]
Hello, I just updated the summary to match the original file and also changed the # and ## from my file to match your style. Is it ok now?

**Pull request merged**
